### ISSUE TITLE
UnhandledPromiseRejectionWarning: TypeError: nightmare.onBeforeRequest is not a function

### ISSUE THREAD

**Issue by nowrap** [kyungw00k/nightmare-webrequest-addon#5]
Why is this happening?

```
const Nightmare = require('nightmare');
require('nightmare-webrequest-addon');
```

```
nightmare
	.onBeforeRequest(function (details, callback) {
		console.log("details", details);
	})
```

**Comment by mmsanalytics** [comment]
I'm experiencing the same issue.

**Comment by mmsanalytics** [comment]
@nowrap I couldn't get it to work with this package, but all I had to do was implement my own custom Nightmare action, like:
`Nightmare.action( 'onBeforeRequest',
  function(name, options, parent, win, renderer, done) { // Define the action to run inside Electron
    win.webContents.session.webRequest.onBeforeRequest((details, cb) => {
      parent.call('onBeforeRequest', details, res => { // call our event handler
        res ? cb(Object.assign({}, res)) : cb({ cancel: false });
      })
    });
    done();
  },
  function(handler, done) {
    // listen for "onBeforeRequest" events
    this.child.respondTo('onBeforeRequest', handler);
    done();
  }
);
//
// onBeforeRequest`

Thanks to @matthewmueller here:
https://github.com/segmentio/nightmare/issues/1308

**Comment by kyungw00k** [comment]
I just publish 1.0.1, and it looks fine now.

```
const Nightmare = require('nightmare');
require('nightmare-webrequest-addon');

const nightmare = Nightmare()

nightmare
	.onBeforeRequest(function (details, callback) {
		console.log("details", details);
	})
```
