### ISSUE TITLE
version 1.0.1 broke compatibility with Nightmare 2.x

### ISSUE THREAD

**Issue by wojtekmaj** [kyungw00k/nightmare-webrequest-addon#7]
Hello,
you seem to have updated `nightmare` in `dependencies`. This, sadly, causes Nightmare 2.x users to have two copies of Nightmare installed - one by themselves, another by nightmare-webrequest-addon. Obviously, everything stops working.

I suggest a following fix:
`"nightmare": "^2.3.4 || ^3.0.0"

Or even, on top of that, move `nightmare` to `peerDependencies` to completely stop npm from installing nightmare and expect the user to do so manually. `peerDependencies` will make sure that compatible version of Nightmare is installed and the user will be warned if they run incompatible version.

This normally would be fine, but in this case, you've updated only bugfix version number, suggesting that this is a change that won't break anything for anyone. Should you want to deprecate nightmare 2.x for some reason, You should definitely go and release version 2.0.0. However, I don't see a reason for you to do so - it should work fine for older Nightmare as well.

**Comment by kyungw00k** [comment]
Please check the version 1.0.2.
Thanks for reporting!
